networks:
  # This net ensures that each container has a defined static IP.
  # Usage of the service name as IP is not valid for PX4 initialization scripts.
  px4_ros_com_ros2_net:
    ipam:
      driver: default
      config:
        - subnet: ${NET_SUBMASK}

  # This net is to enable connection to host ports directly. Using only the net
  # with static IPs doen't allow the containers to connect to the internet.
  hostnet:

services:      
  px4:
    image: ${PX4_IMAGE}:${PX4_TAG}

    env_file: .env

    volumes:
      - ${X11_VOLUME}
      # - ${PWD}/px4-rc.mavlink:/root/PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/px4-rc.mavlink
      # - ${PWD}/px4-rc.rtps:/root/PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/px4-rc.rtps
      # - ${PWD}/px4-rc.simulator:/root/PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/px4-rc.simulator
      # - ${PWD}/px4-rc.params:/root/PX4-Autopilot/ROMFS/px4fmu_common/init.d-posix/px4-rc.params

    privileged: true

    tty: true

    container_name: ${PX4_CONT_NAME}

    command: /bin/bash -c "make px4_sitl_rtps gazebo"
    #command: /bin/bash -c "make px4_sitl_rtps gazebo_iris no_sim=1"

    networks:
      px4_ros_com_ros2_net:
        ipv4_address: ${PX4_IP}

      hostnet:


  ros2:
    image: ${ROS2_IMAGE}:${ROS2_TAG}

    env_file: .env

    tty: true

    entrypoint: "/entrypoint.sh"

    volumes:
      - ${PWD}/entrypoint.sh:/entrypoint.sh
      
    command: /bin/bash 

    container_name: ${ROS2_CONT_NAME}

    networks:
      px4_ros_com_ros2_net:
        ipv4_address: ${ROS2_IP}

      hostnet:


  qground:
    image: ${QGROUND_IMAGE}:${QGROUND_TAG}

    env_file: .env
      
    privileged: true

    container_name: ${QGROUND_CONT_NAME}

    volumes:
      - ${X11_VOLUME}

    networks:
      px4_ros_com_ros2_net:
        ipv4_address: ${QGROUND_IP}

      hostnet:
